- .npmignore
- Changelog.md
- Readme.md
- index.js
- package.json
- test/data/expectedInterfaces.js
- test/data/expectedModule.js
- test/data/ignoredPerson.js
- test/data/ignoredPersonInterfaces.js
- test/data/starWarsModule.js
- util/interface.js
- Support `__typename`
- Add Root entry points
- i.e. `data?: Query | Mutation` and `errors?: Array<error>`
- Bump to v0.1.0
- Add Changelog
> Add __typename and root entry points

- package.json
- test/data/enumSchema.js
- test/data/expectedEnum.js
- test/data/expectedEnumInterfaces.js
- test/test.js
- util/interface.js
> add support for enums

- test/data/expectedInterfaces.js
- test/data/expectedModule.js
- test/data/ignoredPerson.js
- test/data/ignoredPersonInterfaces.js
- test/data/starWarsModule.js
- util/interface.js
Was erroneously "Integer" thanks
closes #9 and replaces #10
> Fix Int type

- Changelog.md
- package.json
> bump version to 0.3.0

- Changelog.md
- index.js
- package.json
> release 0.3.1

- Changelog.md
- index.js
- package.json
> bump to 0.4.0

- util/interface.js
> [Bug Fix] Handle interfaces with no inputField or fields.

- Changelog.md
- package.json
> bump version to 0.5.1

- Changelog.md
- Readme.md
- index.js
> accept stdin and output to stdout

- Changelog.md
- index.js
- package.json
> Fix help being outputted with stdinout

- packages/from-query/src/index.ts
- packages/from-query/src/subtype.ts
- packages/from-schema/src/index.ts
- packages/types/src/index.ts
> fix a bad type definition and prettify code

- packages/from-schema/src/index.ts
> Fix union type on schema

- Readme.md
- packages/cli/src/index.ts
requested by @Anahkiasen here https://github.com/avantcredit/gql2ts/pull/72#issuecomment-318854443
> add ignore typename & fix readme

- packages/from-schema/src/index.ts
> Fix scalar type resolution

- Changelog.md
- __tests__/__snapshots__/from-schema-test.ts.snap
- packages/from-schema/src/index.ts
> use string literal for typename

- package.json
- packages/from-query/package.json
- packages/from-schema/package.json
- packages/util/package.json
- yarn.lock
fix #94 setting explicit 0.12
fix #92
> support graphql >= 0.10 <0.12

- __tests__/__snapshots__/from-schema-test.ts.snap
- packages/from-schema/src/index.ts
fixes https://github.com/avantcredit/gql2ts/pull/95
> Add description to fields

- packages/cli/Readme.md
- packages/cli/src/index.ts
> update readme and actually allow es modules

- __tests__/util-test.ts
- packages/cli/Readme.md
- packages/cli/src/index.ts
- packages/util/src/fileIO.ts
- packages/util/src/index.ts
> allow graphql schema as an input on cli

- packages/cli/src/index.ts
> always use filename if present

- .travis.yml
- appveyor.yml
> test against node 9

- __tests__/__snapshots__/from-schema-test.ts.snap
- __tests__/from-schema-test.ts
- __tests__/shared/simpleSchema.ts
- packages/cli/src/index.ts
- packages/from-schema/src/index.ts
> add JSDoc tags

- package.json
- packages/language-typescript/package.json
- yarn.lock
> lock typescript < 2.7.0

- __tests__/__snapshots__/from-schema-test.ts.snap
- packages/from-schema/src/index.ts
> generate argument interface for @gql2ts/from-schema

- Changelog.md
- __tests__/__snapshots__/from-schema-test.ts.snap
- packages/from-schema/src/index.ts
- yarn.lock
> fix input field detection & args

- Changelog.md
- package.json
- packages/from-query/package.json
- packages/from-schema/package.json
- packages/util/package.json
- yarn.lock
> loosen restriction on graphql to <1.0.0

- packages/from-query/package.json
- packages/from-schema/package.json
- packages/util/package.json
> move graphql to peer dependency

- __tests__/__snapshots__/from-query-mutations-test.ts.snap
- __tests__/__snapshots__/from-query-normalSchema-test.ts.snap
- __tests__/__snapshots__/from-schema-test.ts.snap
- __tests__/__snapshots__/util-test.ts.snap
- __tests__/from-query-normalSchema-test.ts
- __tests__/from-schema-test.ts
- __tests__/util-test.ts
- packages/from-query/src/index.ts
- packages/from-schema/src/index.ts
- packages/language-flow/src/__tests__/__snapshots__/index-test.ts.snap
- packages/language-flow/src/__tests__/index-test.ts
- packages/language-flow/src/index.ts
- packages/language-typescript/src/__tests__/__snapshots__/index-test.ts.snap
- packages/language-typescript/src/__tests__/index-test.ts
- packages/language-typescript/src/index.ts
- packages/types/src/index.ts
- packages/util/src/index.ts
- packages/util/src/util.ts
> use native enums

- Changelog.md
- __tests__/__snapshots__/from-query-normalSchema-test.ts.snap
- __tests__/util-test.ts
- packages/from-query/__tests__/__snapshots__/from-query-test.ts.snap
- packages/from-query/__tests__/from-query-test.ts
- packages/from-query/src/index.ts
- packages/from-schema/src/index.ts
- packages/util/src/index.ts
- packages/util/src/schema.ts
> get specific typename

- lerna.json
- packages/cli/package.json
- packages/from-query/package.json
- packages/from-schema/package.json
- packages/language-flow/package.json
- packages/language-typescript/package.json
no longer need typescript after #137
> rm typescript dependency for @gql2ts/language-typescript

- .travis.yml
- __tests__/__snapshots__/from-schema-test.ts.snap
- __tests__/data/starWarsSchema.ts
- appveyor.yml
- package.json
- packages/cli/package.json
- packages/from-query/__tests__/__snapshots__/from-query-test.ts.snap
- packages/from-query/package.json
- packages/from-schema/package.json
- packages/util/package.json
- yarn.lock
> support v14

- Readme.md
- packages/from-query/Readme.md
- packages/from-schema/Readme.md
Should make it more clear what the project can do for people who find the github repo and not the published packages ;)
> improve main Readme

- Readme.md
> Add a "Reviewed by Hound" badge
